[unix_http_server]
file={{ user_home }}/.supervisor/run/supervisor.sock
chmod=0700

[supervisord]
logfile={{ user_home }}/.supervisor/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=5
loglevel=info
pidfile={{ user_home }}/.supervisor/run/supervisord.pid
nodaemon=false
silent=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://{{ user_home }}/.supervisor/run/supervisor.sock

[include]
files = {{ user_home }}/.config/supervisord/conf.d/*.ini
