name: forgejo

services:
  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:15
    ports:
      - '127.0.0.1:3100:3100'
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
