name: gatus

services:
  gatus:
    image: docker.io/twinproduction/gatus:v5.36.0
    container_name: gatus
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./config:/config:ro
      - ./data:/data
    environment:
      GATUS_CONFIG_PATH: /config/config.yaml
